### ISSUE TITLE
PhoneGap

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub-Android#1]
@thatoddmailbox I am using [phonegap](http://phonegap.com/) for the iOS app and it also makes android apps so do you want to merge the projects?

**Comment by thatoddmailbox** [comment]
@nywillb I was planning on this to be a separate, native app. I personally do not like PhoneGap because you can't easily make mobile apps that look like they belong to the OS.

**Comment by willbarkoff** [comment]
@thatoddmailbox Okay, but I don't know anything about objective-c or swift, so good luck!

**Comment by thatoddmailbox** [comment]
@nywillb I can do Objective-C-kind of (it is similar to C but funky syntax). But Android apps are in Java.

**Comment by willbarkoff** [comment]
@thatoddmailbox Oh I thought that this was the ios app issue. Sorry.
